name: Test

on: pull_request

jobs:
  test:
    # strategy:
    #   matrix:
    #     node-version: ["22.7.0"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Type Check
        run: bun run tsc

      - name: Run Tests
        run: bun run test:ci

      - name: Run Build
        run: bun run build
